name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: docker login
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Build the Docker image
      run: docker build -t docker-img .
    - name: Tags
      run: |
          docker tag docker-img ${{ secrets.DOCKER_USERNAME }}/docker-img:latest
    - name: Push
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-img:latest
